[package]
name = "automac_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "automac"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
synthesizer = { path = "../synth_learning", version = "0.1.0" }
mlua = { version = "0.8.8", features = ["module", "luajit", "vendored"] }
